name: Monthly ECHO Download

on:
  schedule:
    # Runs at 3 AM on the 1st of every month
    - cron: '0 3 1 * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  download-echo-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests openpyxl
    
    - name: Create output directory
      run: mkdir -p outputs
    
    - name: Run ECHO data processor
      run: python process.py
    
    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: water-violations-${{ github.run_number }}
        path: outputs/*.csv
        retention-days: 90
        if-no-files-found: warn
    
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add outputs/*.csv || echo "No files to add"
        git diff --staged --quiet || git commit -m "Add ECHO data from run ${{ github.run_number }}"
        git push || echo "Nothing to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
